name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config --global user.email "onkar.p@antino.com"
          git config --global user.name "onkarpasrichaa"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          TAG=$('%H%M')
          docker build -t onkarpasrichaa/python_app:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push onkarpasrichaa/python_app:$TAG
          sed -i "s/onkarpasrichaa\/python_app:[0-9]*/onkarpasrichaa\/python_app:$TAG/g" Dockerfile
          git add Dockerfile
          git commit -m "Update image tag to $TAG" || true
          git push origin main

      - name: Update Image Tag Values
        run: |
         git clone https://github.com/OnkarPasrichaa/helm.git
         TAG=$('%H%M')
         # ls | grep helm
         cd helm
         chart_dir="charts/python_app"
         new_image_tag=${{ github.sha }}
         sed -i "s/^  tag: .*/  tag: $TAG/" "$chart_dir/values.yaml"

      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.HELM_REPO_ACCESS_TOKEN}}
        with:
          source-directory: helm/
          destination-github-username: onkarpasrichaa
          destination-repository-name: helm
          user-email: onkar.p@antino.com
          target-branch: "main"
