name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config --global user.email "onkar.p@antino.com"
          git config --global user.name "onkarpasrichaa"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get commit count
        id: commit_count
        run: echo "::set-output name=COUNT::$(git rev-list --count HEAD)"

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          COMMIT_COUNT=$(echo "${{ steps.commit_count.outputs.COUNT }}")
          docker build -t onkarpasrichaa/python_app:$COMMIT_COUNT .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push onkarpasrichaa/python_app:$COMMIT_COUNT
          sed -i "s/onkarpasrichaa\/python_app:[0-9]*/onkarpasrichaa\/python_app:$COMMIT_COUNT/g" Dockerfile
          git add Dockerfile
          git commit -m "Update image tag to $COMMIT_COUNT" || true
          git push origin main
      - name: Update Helm Chart
        env:
          HELM_CHART_REPO: 'https://github.com/onkarpasrichaa/helm'
        run: |
          TAG=$(grep -oP '(?<=onkarpasrichaa/python-app:)[\d.]+' Dockerfile)
          sed -i "s/onkarpasrichaa\/python-app:[\d.]*/onkarpasrichaa\/python-app:$TAG/g" helm/charts/python_app/values.yaml
          git add helm/charts/python_app/values.yaml
          git commit -m "Update image tag to $TAG"
          git push $HELM_CHART_REPO main
