on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx (optional)
        uses: docker/setup-buildx-action@v1

      - name: Get commit count
        id: commit_count
        run: echo "::set-output name=COUNT::$(git rev-list --count HEAD)"

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          COMMIT_COUNT=$(echo "${{ steps.commit_count.outputs.COUNT }}")
          sed -i "s/onkarpasrichaa\/python-app:[0-9]*/onkarpasrichaa\/python-app:$COMMIT_COUNT/g" Dockerfile
          docker build -t onkarpasrichaa/python-app:$COMMIT_COUNT .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push onkarpasrichaa/python-app:$COMMIT_COUNT
          git add Dockerfile
          git commit -m "Update image tag to $COMMIT_COUNT" || true
          git push origin main

      - name: Update Helm Chart (if Docker image tag changed)
        run: |
          # Get current image tag from Dockerfile
          OLD_IMAGE_TAG=$(grep -oP '(?<=onkarpasrichaa/python-app:)[\d.]+' Dockerfile)

          # Get new image tag from the image name after building
          NEW_IMAGE_TAG=$(docker images onkarpasrichaa/python-app:latest | awk '{print $1}')

          # Check if the tag actually changed before committing
          if [[ "$OLD_IMAGE_TAG" != "$NEW_IMAGE_TAG" ]]; then
            git config user.name "GitHub Actions"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout main
            sed -i "s/onkarpasrichaa\/python-app:$OLD_IMAGE_TAG/onkarpasrichaa\/python-app:$NEW_IMAGE_TAG/g" helm/charts/python_app/values.yaml
            git add helm/charts/python_app/values.yaml
            git commit -m "Update image tag to $NEW_IMAGE_TAG (built on $(date +%Y-%m-%d-%H%M%S))"
            git push origin main
          fi
