name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config --global user.email "onkar.p@antino.com"
          git config --global user.name "onkarpasrichaa"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get commit count
        id: commit_count
        run: echo "::set-output name=COUNT::$(git rev-list --count HEAD)"

      - name: Build and push Docker image
