on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (optional)
        run: |
          python -m ensurepip --upgrade --quiet
          pip install -r requirements.txt  # Replace with your actual install command

      - name: Set up Docker Buildx (optional)
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image (assuming Dockerfile is present)
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t onkarpasrichaa/python_app:latest .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin  # Masked password
          docker push onkarpasrichaa/python_app:latest

      - name: Update Helm Chart (if Docker image tag changed)
        uses: nlopes/git-action@v3  # Use dedicated action for Git operations
        env:
          HELM_CHART_REPO: 'https://github.com/OnkarPasrichaa/helm.git'
          ACCESS_TOKEN: ${{ secrets.HELM_REPO_ACCESS_TOKEN }}  # Dedicated token for Helm repo
        run: |
          git fetch origin main
          OLD_IMAGE_TAG=$(grep -oP '(?<=onkarpasrichaa/python-app:)[\d.]+' helm/charts/python_app/values.yaml)
          docker image inspect onkarpasrichaa/python_app:latest | jq -r '.[0].Created' > image_creation_date.txt
          NEW_IMAGE_TAG=$(date +%Y-%m-%d-%H%M%S)  # Generate unique tag based on timestamp

          if [[ "$OLD_IMAGE_TAG" != "latest" ]]; then  # Only update if tag has changed
            git config user.name "onkarpasrichaa"
            git config user.email "onkar.p@antino.com"
            git checkout main
            sed -i "s/onkarpasrichaa\/python-app:$OLD_IMAGE_TAG/onkarpasrichaa\/python-app:$NEW_IMAGE_TAG/g" helm/charts/python_app/values.yaml
            git add helm/charts/python_app/values.yaml
            git commit -m "Update image tag to $NEW_IMAGE_TAG (built on $(cat image_creation_date.txt))"
            git push origin main
          fi

