name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install git
        run: apt-get update && apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config --global user.email "onkar.p@antino.com"
          git config --global user.name "onkarpasrichaa"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          docker buildx build --platform linux/amd64 -t onkarpasrichaa/python_app:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push onkarpasrichaa/python_app:$TAG
          sed -i "s/onkarpasrichaa\/python_app:[0-9]*/onkarpasrichaa\/python_app:$TAG/g" Dockerfile
          git add Dockerfile
          git commit -m "Update image tag to $TAG" || true
          git push origin main
